version: "3"
services:
  hub:
    image: seleniarm/hub:4.9.0  #selenium/hub:4.9.0
    ports:
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:latest     #selenium/node-chrome:latest
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444/
